Capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from markdownx import urls as markdownx
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kapchikachi.urls', namespace="kapchikachi")),
    path('markdownx/', include('markdownx.urls')),
    path('common/', include('common.urls', namespace="common")),
    # path('', include('kapchikachi.urls')), #입력 안하면 자동으로 kapchokachi로 이동

    #소셜로그인 기능
    path('accounts/', include('allauth.urls')),

    #정적파일처리
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views, templates

app_name='common'

urlpatterns = [ #함수는 그냥 호출 / 클래스는 클래스명.as_view() 처리
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('record/', views.user_purchase, name='user_purchase'),
    # path('record/', views.PurchaseList.as_view(), name='PurchaseList'),
    #테스트용
    # path('signup2/', views.UserCreate.as_view()),
    # path('api-auth/', include('rest_framework.urls')),
]

kapchikachi/urls.py
from django.urls import path, include
from . import views
from .views import*
from django.views import View

app_name='kapchikachi'


urlpatterns = [ #함수는 그냥 호출 / 클래스는 클래스명.as_view() 처리
    # path('main/',views.main_html, name='main'),
    ###메인 페이지 노출& 그래프, 댓글 노출###
    path('',views.GetChart, name='main'),

    ###운영진 소개###
    path('aboutus/', views.About_us, name='aboutus'),

    ###결제 유형 선택 페이지###
    path('SelectPayOption/', views.SelectPayOption, name='SelectPayOption'), #추가할 url페이지

    ###구매 페이지 시스템###
    path('purchase/', views.CommentCreate, name='CommentCreate'),
    path('pastinfo/', views.Find_past_info, name='FindPastInfo'), #기존 구매 이력창으로 넘기는 url
    path('check/', views.CheckBeforeSell, name='check'),
    path('checkbill/', views.Deposit, name="check_bill"),

    ####결제 시스템####
    # path('pay/', views.pay, name="pay"),
    ####아엠포트####
    path('charge/', views.purchase_order, name='purchase_order'),
    path('checkout/', views.OrderCheckoutAjaxView, name='order_checkout'),
    path('validation/', views.OrderImpAjaxView, name='order_validation'),

    path('payment/', views.real_sell, name="real_sell"),
    # path('checkbill/', views.check_bill, name="check_bill"),

    ####구매이력확인####
    path('personal/', views.Check_personal_buy, name='Check_personal_buy'),
    path('notfound_buy/', views.notfound_buy, name='notfound_buy'),

    ####사업자정보고지용####
    path('noticeinfo/', views.Notice_info, name='Notice_info'),
    path('qna/', views.Qna, name='Qna'),#고동현이 추가
    ####관리자용 페이지####
    path('download/', views.GetData, name='GetData'),
    path('delete/', views.DeleteData, name='DeleteData'),

    #상품목록
    path('dogairpod1/',views.Airpoddog1, name='DogAirpod12'),
    path('dogairpod2/', views.Airpoddog2, name='DogAirpodpro'),
    path('catairpod1/', views.Airpodcat1, name='CatAirpod12'),
    path('catairpod2/', views.Airpodcat2, name='CatAirpodpro'),
    path('dogkeyring/', views.KeyringDog, name='DogKeyring'),
    path('catkeyring/', views.KeyringCat, name='CatKeyring'),
     path('products/', views.Products, name='Products'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class Userinfo(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    # username = models.CharField(max_length=200,blank=True)
    # created = models.DateTimeField(auto_now_add=True)  # 작성시간
    email = models.EmailField(blank=True)
    gender_method=(
        (None,'선택'),
        ('0','남성'),
        ('1','여성')
    )
    gender = models.CharField(max_length=1, choices=gender_method, null=False, blank=False)
    birth = models.DateField(blank=True)



# class UserManager(BaseUserManager):
#     # 일반 user 생성
#     def create_user(self, email, gender, birth, password=None):
#         if not email:
#             raise ValueError('이메일을 입력해주세요.')
#         if not gender:
#             raise ValueError('성별을 선택해주세요.')
#         if not birth:
#             raise ValueError('생년월일을 지정해주세요.')
#         user = self.model(
#             email=self.normalize_email(email),
#
#         )
#         user.set_password(password)
#         user.save(using=self._db)
#         return user
#
#     # 관리자 user 생성
#     def create_superuser(self, email, gender, birth, password=None):
#         user = self.create_user(
#             email,
#             password=password,
#             gedner=gender,
#             birth=birth
#         )
#         user.is_admin = True
#         user.save(using=self._db)
#         return user


# class User(AbstractBaseUser):
#     id = models.AutoField(primary_key=True)
#     email = models.EmailField(default='', max_length=100, null=False, blank=False, unique=True)
#     gender_method=(
#         (None, '선택'),
#         ('0','남성'),
#         ('1','여성')
#     )
#     gender = models.CharField(max_length=1, choices=gender_method, null=False, blank=False)
#     birth = models.DateField(null=False, blank=False)
#
#     # User 모델의 필수 field
#     is_active = models.BooleanField(default=True)
#     is_admin = models.BooleanField(default=False)
#
#     # 헬퍼 클래스 사용
#     objects = UserManager()
#
#     # 사용자의 username field는 id로 설정
#     USERNAME_FIELD = 'id'
#     # 필수로 작성해야하는 field
#     REQUIRED_FIELDS = ['email', 'gender', 'birth']
#
#     def __str__(self):
#         return self.id

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Userinfo


YEARS= [x for x in range(1940,2022)]

class UserForm(UserCreationForm):
    # email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username",)#, "email")
        # labels = {
        #     'email' : '이메일'
        # }

class UserinfoForm(forms.ModelForm):
    birth = forms.DateField(label='생년월일을 입력하세요.', initial="2021-11-16", widget=forms.SelectDateWidget(years=YEARS))
    class Meta:
        model = Userinfo
        fields = ["gender", "birth", "email"]
        labels = {
            'gender' : '성별',
            'birth' : '생년월일',
            'email' : 'email'
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import *
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from kapchikachi.models import Comment
from django.views.generic import ListView

#테스트용
# from django.shortcuts import render
# #from .serializers import UserSerializer
# from .models import User
# from rest_framework import generics


# Create your views here.
# class UserCreate(generics.CreateAPIView):
#     queryset = User.objects.all()
    #serializer_class = UserSerializer
#테스트용

# def signup1(request):
#     if request.method=='POST':
#         user_form=UserForm(request.POST)
#         # userinfo_form = UserinfoForm(request.POST)
#         if user_form.is_valid():
#             user_form.save() #회원가입 정보 저장
#             # userinfo_form.save()
#
#             username=user_form.cleaned_data.get('username')
#             raw_password=user_form.cleaned_data.get('password1')
#
#             #회원가입한 유저 로그인 처리
#             user=authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('kapchikachi:CommentCreate')
#             # return redirect('./kapchikachi/purchase/') #회원가입 후 로그인되면, 구매페이지로 이동
#
#         else:
#             # context = {
#             #     'user_form': UserForm(),
#             #     'userinfo_form': UserinfoForm(),
#             # }
#             #user_form=UserForm()
#             # userinfo_form=UserinfoForm()
#             return redirect('kapchikachi:aboutus')
#     user_form = UserForm()
#     return render(request, 'common/signup.html', {'user_form':user_form}) #, 'userinfo_form':userinfo_form})

def signup(request):
    if request.method=='POST':
        form1 = UserForm(request.POST)
        form2 = UserinfoForm(request.POST)
        # if form1.is_valid():# and form2.is_valid():

        if request.POST['password1']==request.POST['password2']:

            user=User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])

            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')

            #저장된 User 호출
            this_user = request.user.id
            user = User.objects.get(id=this_user)

            tmp_birth_year =request.POST['birth_year']
            tmp_birth_month =request.POST['birth_month']
            tmp_birth_day = request.POST['birth_day']
            user_birth=tmp_birth_year+'-'+tmp_birth_month+'-'+tmp_birth_day

            userinfo = Userinfo.objects.create(username=user, email=request.POST['email'], gender=request.POST['gender'], birth=user_birth )
            userinfo.save()
            # result={'this_user':request.POST['username']}

            return redirect('kapchikachi:CommentCreate')
        #else:
        #    raise ValueError('입력 값을 확인해주세요.')
    else:
        form1 = UserForm()
        form2 = UserinfoForm()
        # 'userinfo_form': UserinfoForm(),
    return render(request, 'common/signup.html', {'user_form':form1, 'userinfo_form':form2})


# 유저 정보
# @login_required(login_url='common:login')
# def user_info(request):
#     all_data=Comment.objects.all()
#     db_num = len(all_data)
#
#     user_num = 0  # 현재 로그인한 유저 식별 번호(전체 데이터 중 현재 유저의 데이터 위치 인덱스 반환)
#     user_purchase_num = 0
#
#     # 현재 로그인 유저의 데이터 식별기능
#     for a in range(db_num):
#         if (str(all_data[a].author) == str(request.user.username)) and (
#                 int(all_data[a].sell) > 0):  # 현재 로그인 유저의 데이터 인덱스 번호 조회
#             user_num +=a
#             user_purchase_num += 1
#
#     user_name = str(all_data[a].author)
#
#     user_product_type = []
#     user_purchase_amount = []
#
#     for b in range(user_purchase_num):
#
#



# 유저 구매내역
@login_required(login_url='common:login')
def user_purchase(request):
    all_data=Comment.objects.all()
    db_num = len(all_data)

    user_data=[[0,0,0,0,0] for col in range(db_num)]
    user_num=[] #현재 로그인한 유저 식별 번호(전체 데이터 중 현재 유저의 데이터 위치 인덱스 반환)
    user_purchase_num=0

    #현재 로그인 유저의 데이터 식별기능
    for a in range(db_num):
        if (str(all_data[a].author) == str(request.user.username)) and (int(all_data[a].sell) >0): #현재 로그인 유저의 데이터 인덱스 번호 조회
            user_num.append(a)
            user_purchase_num+=1
        else:
            return render(request, 'common/user_purchase_none.html')

    #구매내역이 1번이라도 있는 경우
    if user_purchase_num>0:
        check=0
        user_purchase_time=[]
        user_product_type=[]
        user_purchase_amount=[]
        user_receiver_name=[]
        user_receiver_phone=[]
        user_receiver_address=[]
        #각각의 구매내역을 result에 추가
        for b in range(user_purchase_num):
            #구매정보
            # user_name=self.request.user.username#유저이름(식별용)
            this_purchase_time=str(all_data[user_num[b]].created) #구매일자

            this_receiver_name=all_data[user_num[b]].receiver_name #수취인 성함
            this_receiver_phone=all_data[user_num[b]].receiver_phone #수취인 번호
            this_receiver_address = all_data[user_num[b]].detail_address #수취인 주소(상세주소)

            #구매상품
            this_product_type = []  # 구매상품 종류

            if all_data[user_num[b]].dog_strap > 0:
                this_product_type.append(f'강아지 스트랩 {all_data[user_num[b]].dog_strap}개')
            if all_data[user_num[b]].dog_case > 0:
                this_product_type.append(f'강아지 케이스 {all_data[user_num[b]].dog_case}개')
            if all_data[user_num[b]].cat_strap > 0:
                this_product_type.append(f'고양이 스트랩 {all_data[user_num[b]].cat_strap}개')
            if all_data[user_num[b]].cat_case > 0:
                this_product_type.append(f'고양이 케이스 {all_data[user_num[b]].cat_case}개')

            #구매금액
            this_purchase_amount=all_data[user_num[b]].sell

            #반환값
            user_purchase_time.append(this_purchase_time)
            user_product_type.append(this_product_type)
            user_purchase_amount.append(this_purchase_amount)
            user_receiver_name.append(this_receiver_name)
            user_receiver_phone.append(this_receiver_phone)
            user_receiver_address.append(this_receiver_address)

            # result={
            #     'user_name':user_name,
            #     'user_purchase_time':user_purchase_time,
            #     'user_product_type':user_product_type,
            #     'user_purchase_amount':user_purchase_amount,
            #     'user_receiver_name':user_receiver_name,
            #     'user_receiver_phone':user_receiver_phone,
            #     'user_receiver_address':user_receiver_address,
            # }

        # total_num=[]
        # for i in range(user_purchase_num):
        #     total_num.append(str(i))
        total_num=int(user_purchase_num)

        result={
            'user_purchase_time':user_purchase_time,
            'user_product_type':user_product_type,
            'user_purchase_amount':user_purchase_amount,
            'user_receiver_name':user_receiver_name,
            'user_receiver_phone':user_receiver_phone,
            'user_receiver_address':user_receiver_address,
            'total_num':total_num,
        }


        return render(request,'common/user_purchase.html', context=result) #호출 시 for문으로 각 아이템별 호출 필요

    # return render(request,'common/user_purchase_none.html')

# 유저 구매내역
@login_required(login_url='common:login')
class PurchaseList(ListView):
    model=Comment

    def get_queryset(self):
        return Comment.objects.order_by('-created')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PurchaseList, self).get_context_data(**kwargs)
        context['category_list'] = Comment.objects.filter(author=self.user.username)
        return context

common/templates/common/formerrors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div>
    <strong>{{field.label}}</strong>
    {{error}}
</div>
{% endfor %}
{% endfor %}

{% for error in form.non_field_errors %}
<div>
    <strong>{{error}}</strong>
</div>
{% endfor %}
{% endif %}

common/templates/common/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>로그인</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>같이가치</title>
    {% load static %}
    <link rel="stylesheet" href = "{%static 'css/styles.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script type = "text/javascript" src = "https://d3js.org/d3.v4.min.js"></script>
    <!--자동 업데이트 로직(수정 금지)-->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
    <script type="text/javascript">
 // var auto_refresh = setInterval(
 // function ()
 // {
   //   $('#load_tweets').load('refresh.html').fadeIn("slow");
//}, 5000);
</script>
    <!--자동 업데이트 로직(수정 금지)-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/
  Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</head>


<body style="margin: 0;">

<!--  회원가입 기능-->

<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="login-form">

            <a href="{% url 'kapchikachi:main' %}"><div class="img-fluid"><img src="{%static 'img/valto.png'%}" style=" width: 150px;max-height: 150px;"></div></a>

{% load crispy_forms_tags %}
            <!--  로그인 창 구현-->
            <div class="form-group">
                <form method="post" class="post-form" action="{% url 'common:login' %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    {% include "./formerrors.html" %}
                    <input type="text" class="form-control" name="username" id="username"
                           placeholder="ID"  value="{{ form.username.value|default_if_none:'' }}" style="width: 260px">
                    <input type="password" class="form-control" name="password" id="password"
                           placeholder="비밀번호"  value="{{ form.password.value|default_if_none:'' }}"style="width: 260px">
                    <button type="submit" class="submit-btn"style="width: 260pxs;font-family:GyeonggiTitleM; ;"><b>로그인</b></button>


                </form>
            </div>
            <div class="links">
                <a href="{% url 'common:signup' %}" style="font-family:GyeonggiTitleM; ;"><b>회원가입 / </b></a>
                <a href="{% url 'kapchikachi:Notice_info' %}" style="font-family:GyeonggiTitleM; ;"><b>이용약관</b></a>
            </div>
            <div class="links">
                {% load socialaccount %}
                {% if request.user.is_authenticated %}
                <p>{{ request.user.username }}</p>
                <br>
                <a href="{% url 'common:logout' %}" style="font-family:GyeonggiTitleM; ;">로그아웃</a>
                <br>
                <!--    개인 계정 페이지로 이동(개인정보확인 및 수정/ 구매내역 확인)-->
                {% else %}
                <a href="{% provider_login_url 'naver' %}"><img src="{%static 'img/naver.png'%}" style="width: 25px;height: 25px;margin-left: 2px;"></a>

                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>
</div>
<!----sns 로그인 구현 예정-->
<div class="row"></div>
</body>
</html>

common/templates/common/user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>개인정보</title>
</head>
<body>

<!--유저표시-->

<!--유저정보 확인 및 수정 페이지-->

<!--구매이력 확인 페이지-->

</body>
</html>

common/templates/common/user_purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>구매내역</title>
</head>
<body>

<!--로그인한 사용자 식별용-->
{% if request.user.is_authenticated %}
    <p>{{ request.user.username }}</p>
{% endif %}


{{total_num}}
{% for a in total_num %}
<!--유저표시-->


<div>
    <!--구매일자-->
구매일시:
<br>
{{ user_purchase_time.a }}

</div>

<br>
<div>
    <!--구매상품-->
구매상품:
<br>
    {% for b in user_product_type %}
    {{ b }}
    {% endfor %}
</div>

<br>
<div>
    <!--구매가격-->
구매가격:
<br>
{{ user_purchase_amount.a }}
</div>

<br>
<div>
    <!--수취인성함-->
수취인성함:
<br>
{{ user_receiver_name.a }}
</div>

<br>
<div>
    <!--수취인번호-->
수취인번호:
<br>
{{ user_receiver_phone.a }}
</div>

<br>
<div>
    <!--상세주소-->
상세주소:
<br>
{{ user_receiver_address.a }}
</div>

{% endfor %}
</body>
</html>

common/templates/common/user_purchase_none.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>구매내역</title>
</head>
<body>

<h1>죄송합니다. 구매내역을 조회하지 못했습니다.</h1>
</body>
</html>