Capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from markdownx import urls as markdownx
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kapchikachi.urls', namespace="kapchikachi")),
    path('markdownx/', include('markdownx.urls')),
    path('common/', include('common.urls', namespace="common")),
    # path('', include('kapchikachi.urls')), #입력 안하면 자동으로 kapchokachi로 이동

    #소셜로그인 기능
    path('accounts/', include('allauth.urls')),

    #정적파일처리
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views, templates

app_name='common'

urlpatterns = [ #함수는 그냥 호출 / 클래스는 클래스명.as_view() 처리
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('record/', views.user_purchase, name='user_purchase'),
    # path('record/', views.PurchaseList.as_view(), name='PurchaseList'),
    #테스트용
    # path('signup2/', views.UserCreate.as_view()),
    # path('api-auth/', include('rest_framework.urls')),
]

kapchikachi/urls.py
from django.urls import path, include
from . import views
from .views import*
from django.views import View

app_name='kapchikachi'


urlpatterns = [ #함수는 그냥 호출 / 클래스는 클래스명.as_view() 처리
    # path('main/',views.main_html, name='main'),
    ###메인 페이지 노출& 그래프, 댓글 노출###
    path('',views.GetChart, name='main'),

    ###운영진 소개###
    path('aboutus/', views.About_us, name='aboutus'),

    ###결제 유형 선택 페이지###
    path('SelectPayOption/', views.SelectPayOption, name='SelectPayOption'), #추가할 url페이지

    ###구매 페이지 시스템###
    path('purchase/', views.CommentCreate, name='CommentCreate'),
    path('pastinfo/', views.Find_past_info, name='FindPastInfo'), #기존 구매 이력창으로 넘기는 url
    path('check/', views.CheckBeforeSell, name='check'),
    path('checkbill/', views.Deposit, name="check_bill"),

    ####결제 시스템####
    # path('pay/', views.pay, name="pay"),
    ####아엠포트####
    path('charge/', views.purchase_order, name='purchase_order'),
    path('checkout/', views.OrderCheckoutAjaxView, name='order_checkout'),
    path('validation/', views.OrderImpAjaxView, name='order_validation'),

    path('payment/', views.real_sell, name="real_sell"),
    # path('checkbill/', views.check_bill, name="check_bill"),

    ####구매이력확인####
    path('personal/', views.Check_personal_buy, name='Check_personal_buy'),
    path('notfound_buy/', views.notfound_buy, name='notfound_buy'),

    ####사업자정보고지용####
    path('noticeinfo/', views.Notice_info, name='Notice_info'),
    path('qna/', views.Qna, name='Qna'),#고동현이 추가
    ####관리자용 페이지####
    path('download/', views.GetData, name='GetData'),
    path('delete/', views.DeleteData, name='DeleteData'),

    #상품목록
    path('dogairpod1/',views.Airpoddog1, name='DogAirpod12'),
    path('dogairpod2/', views.Airpoddog2, name='DogAirpodpro'),
    path('catairpod1/', views.Airpodcat1, name='CatAirpod12'),
    path('catairpod2/', views.Airpodcat2, name='CatAirpodpro'),
    path('dogkeyring/', views.KeyringDog, name='DogKeyring'),
    path('catkeyring/', views.KeyringCat, name='CatKeyring'),
     path('products/', views.Products, name='Products'),
]

kapchikachi/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields=['receiver_name','receiver_phone','content', 'dog_case1', 'dog_case2', 'dog_keyring', 'cat_case1', 'cat_case2', 'cat_keyring', 'shipping', 'detail_address', 'hufs','deposit_name']
        labels= {
            'receiver_name': '수취인 성함', #배송받는 분
            'receiver_phone': '수취인 연락처',
            'content': '남기고 싶은 말',
            'dog_case1': '강아지 에어팟1,2 케이스',
            'dog_case2': '강아지 에어팟프로 케이스',
            'dog_keyring': '강아지 키링',
            'cat_case1': '고양이 에어팟1,2 케이스',
            'cat_case2': '고양이 에어팟프로 케이스',
            'cat_keyring': '고양이 키링',
            'shipping': '수령방법 선택', #배송비 책정용
            'detail_address': '배송지 입력',
            'hufs': '외대생 여부',
            'deposit_name': '예금주', #입금하는 사람 이름
            #'cashreceipts': '현금영수증 발급', #현금영수증 발급 여부 -> 동현 프론트 추가 요청(재윤)
            #'cashreceipts_num': '현금영수증 번호'#현금영수증 번호 발급 여부 -> 동현 프론트 추가 요청(재윤)
        }

kapchikachi/views.py
import openpyxl
from django.shortcuts import render, redirect
from django.views import View
import random
from .models import * #모든 모델 상속
from django.views.generic import CreateView #Admin에 띄우면 사용
from openpyxl import Workbook, load_workbook #엑셀DB연결
from .forms import CommentForm #forms의 파일 상속
from django.utils import timezone #시간 설정 패키지
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin #'로그인'에 대한 조건을 담은 클래스
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.http import JsonResponse


#html 연결
def main_html(request): #재윤 기능 test html
    return render(request, 'kapchikachi/index.html')

def thankyou_html(request): #재윤 기능 test html
    return render(request, 'kapchikachi/check.html')

def About_us(request):
    return render(request, 'kapchikachi/about.html')

def notfound_buy(request):
    return render(request, 'kapchikachi/notfound_buy.html')

def Notice_info(request):
    return render(request, 'kapchikachi/Notice_info.html')
def Qna(request):
    return render(request, 'kapchikachi/qna.html') #고동현 추가
#상품목록
def Airpoddog1(request):
    return render(request, 'kapchikachi/products_info1.html')
def Airpoddog2(request):
    return render(request, 'kapchikachi/products_info2.html')
def Airpodcat1(request):
    return render(request, 'kapchikachi/products_info3.html')
def Airpodcat2(request):
    return render(request, 'kapchikachi/products_info4.html')
def KeyringDog(request):
    return render(request, 'kapchikachi/products_info5.html')
def KeyringCat(request):
    return render(request, 'kapchikachi/products_info6.html')
def Products(request):
    return render(request, 'kapchikachi/products.html')

def SelectPayOption(request): #구매 방법 선택(카드결제: 네이버 스토이 이동 / 무통장입금: 우리 구매 페이지 이동)
    return render(request, 'kapchikachi/selectpayoption.html')


###############전역변수 선언###############
login_valid=0 #로그인 값이 유효한지 검사하는 전역변수
count=0 #조회수 체크용

###상품 가격 상품가격 수정(고동현)
price_dog_case1=8900
price_dog_case2=8900
price_dog_keyring=5000
price_cat_case1=8900
price_cat_case2=8900
price_cat_keyring=5000


###상품 원가
cost_dog_case1=6900 #2000원
cost_dag_case2=6900
cost_dog_keyring=4000 #1000원
cost_cat_case1=6900
cost_cat_case2=6900
cost_cat_keyring=4000

#배송비
shipping_fee=2800

#직접수령 장소
pickup_address="한국외국어대학교 글로벌캠퍼스 정문"
direct_pickup="한국외국어대학교 글로벌캠퍼스 정문"

###############기부자들이 로그인 -> 구매 과정###############
@login_required(login_url='common:login')
def CommentCreate(request):

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment=form.save(commit=False)
            comment.created=timezone.now()
            comment.author=request.user

            # 필수 정보 체크용(기존 정보 재 이용 시)
            if comment.receiver_name==None or comment.receiver_phone == None or comment.shipping==None or comment.content==None:
                result = {
                    'form': form,
                    'warning': '입력해주세요!'
                }

                return render(request, 'kapchikachi/comment_form.html', context=result)

            #값이 비어있으면 0으로 변경 null 오류 수정
            if comment.dog_case1 == '0':
                comment.dog_case1 =0

            if comment.dog_case2 == '0':
                comment.dog_case2 =0

            if comment.dog_keyring == '0':
                comment.dog_keyring =0

            if comment.cat_case1 == '0':
                comment.cat_case1 =0

            if comment.cat_case2 == '0':
                comment.cat_case2 =0

            if comment.cat_keyring == '0':
                comment.cat_keyring =0
            
            if comment.dog_case1+comment.dog_case2+comment.dog_keyring+comment.cat_case1+comment.cat_case2+comment.cat_keyring == 0:
                result = {
                    'form': form,
                    'warning_product': '상품을 선택해주세요!'
                }

                return render(request, 'kapchikachi/comment_form.html', context=result)

            #구매자 별 총 상품 금액 데이터형 오류 수정(고동현)

            selled_product = int(float(comment.dog_case1))*price_dog_case1 + int(float(comment.dog_case2))*price_dog_case2 + int(float(comment.dog_keyring))*price_dog_keyring + int(float(comment.cat_case1))*price_cat_case1 + int(float(comment.cat_case2))*price_cat_case2 +int(float(comment.cat_keyring))*price_cat_keyring

            #직접수령 시 배송비 x
            #delivery_fee=0

            if comment.shipping=='1': #택배 이용 시 배송비 책정
                # delivery_fee += int(shipping_fee)
                selled_product += 2800

            #배송방법에 따라 상세주소 입력 여부 결정
            if comment.shipping=='1' and comment.detail_address=='' or comment.detail_address==None  :

                result = {
                    'form': form,
                    'warning_address': '배송받을 주소를 입력해주세요!'
                }

                return render(request, 'kapchikachi/comment_form.html', context=result)

            if comment.shipping=='0':
                comment.detail_address=pickup_address

            # if comment.cashreceipts =='1' and (comment.cashreceipts_num =='' or comment.cashreceipts_num ==None):
            #     result = {
            #         'form': form,
            #         'warning_cashreceipts_num': '현금영수증 발급번호를 입력해주세요!'
            #     }
            #
            #     return render(request, 'kapchikachi/comment_form.html', context=result)

            #구매자 별 총 판매 금액
            total_cost=selled_product #+ delivery_fee

            #구매자 총 판매금액
            comment.sell=total_cost

            #'구매 전'임을 DB에 표시
            comment.real_selled=0

            # 상품 준비중 처리
            comment.shipping_state=0


            #구매자 정보 저장
            comment.save()

            return HttpResponseRedirect('/check/')

        else:
            return render(request, 'kapchikachi/comment_form.html', {'form': form})
    else:
        form=CommentForm()
        result = {
            'form': form,
        }
        return render(request, 'kapchikachi/comment_form.html',context=result)


#####기 구매 이력이 있는 회원정보 호출#####
@login_required(login_url='common:login')
def Find_past_info(request):
    this_receiver_name=''
    this_receiver_phone=''

    if request.method != 'POST':
        this_user=request.user.id

        all_data = Comment.objects.all().order_by('-created') #주문 생성 시점 기준 '내림차순'정렬

        user = User.objects.get(id=this_user)
        before_sell=all_data.filter(author_id=user, real_selled=1)
        if int(before_sell.count())<1:
            form = CommentForm()
            result = {
                'form': form,
                'warning_info': '구매이력이 없습니다. 구매 부탁드립니다!',
            }
            return render(request, 'kapchikachi/comment_form.html', context=result)
        else:
            before_info=before_sell.get()

            this_receiver_name=before_info.receiver_name
            this_receiver_phone=before_info.receiver_phone

            form = CommentForm()
            result = {
                'form':form,
                'this_receiver_name':this_receiver_name,
                'this_receiver_phone':this_receiver_phone,
            }
            return render(request, 'kapchikachi/comment_form2.html', context=result)

    ####POST(Submit)받은 경우
    else:
        form = CommentForm(request.POST)

        if form.is_valid():
            comment=form.save(commit=False)
            comment.created=timezone.now()
            comment.author=request.user
            if this_receiver_name != '' and this_receiver_phone != '':
                comment.receiver_name=this_receiver_name
                comment.receiver_phone=this_receiver_phone

            # 필수 정보 체크용(기존 정보 재 이용 시)
            if comment.shipping==None or comment.content==None:
                result = {
                    'form': form,
                    'this_receiver_name':this_receiver_name,
                    'this_receiver_phone':this_receiver_phone,
                    'warnning': '입력해주세요!'
                }

                return render(request, 'kapchikachi/comment_form.html', context=result)

            #값이 비어있으면 0으로 변경
            if comment.dog_case1 == None:
                comment.dog_case1 =0

            if comment.dog_case2 == None:
                comment.dog_case2 =0

            if comment.dog_keyring == None:
                comment.dog_keyring =0

            if comment.cat_case1 == None:
                comment.cat_case1 =0

            if comment.cat_case2 == None:
                comment.cat_case2 =0

            if comment.cat_keyring == None:
                comment.cat_keyring =0

            #구매자 별 총 상품 금액
            selled_product = comment.dog_case1*price_dog_case1 + comment.dog_case2*price_dog_case2 + comment.dog_keyring*price_dog_keyring + comment.cat_case1*price_cat_case1 + comment.cat_case2*price_cat_case2 + comment.cat_keyring*price_cat_keyring

            #직접수령 시 배송비 x
            deliverty_fee=0

            if comment.shipping=='1': #택배 이용 시 배송비 책정
                # deliverty_fee += shipping_fee
                deliverty_fee += 3500

            #배송방법에 따라 상세주소 입력 여부 결정
            if comment.shipping=='1' and comment.detail_address=='' :

                result = {
                    'form': form,
                    'warnning_address': '배송받을 주소를 입력해주세요!'
                }

                return render(request, 'kapchikachi/comment_form2.html', context=result)

            if comment.shipping=='0':
                comment.detail_address=pickup_address

            #구매자 별 총 판매 금액
            total_cost=selled_product + deliverty_fee

            #구매자 총 판매금액
            comment.sell=total_cost+1000

            #'구매 전'임을 DB에 표시
            comment.real_selled=0

            # 상품 준비중 처리
            comment.shipping_state=0

            #구매자 정보 저장
            comment.save()

            return HttpResponseRedirect('/check/')



#####구매전 재확인#####
@login_required(login_url='common:login')
def CheckBeforeSell(request):

kapchikachi/templates/kapchikachi/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DB초기화(관리자용)</title>
</head>
<body>

<!--DB 전부 리셋-->

<!--쿼리 테이블의 DB 리셋-->
관리자용 비공개 주소입니다.
<br>
<table>
    <a href="{% url 'kapchikachi:DeleteData' %}">
        DB초기화
    </a>
</table>

</body>
</html>

kapchikachi/templates/kapchikachi/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DB다운로드(관리자용)</title>
</head>
<body>

<!--DB다운로드 페이지-->

<!-- DB엑셀로 다운로드 -->
DB 다운로드용 페이지입니다.
<br>
<table>
    <a href="{% url 'kapchikachi:GetData' %}">
        다운로드
    </a>
</table>


</body>
</html>

kapchikachi/templates/kapchikachi/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>구매</title>
</head>
<body>

<button type="submit">구매하기</button>
<a href="{% url 'kapchikachi:main' %}">취소</a>


</body>
</html>

kapchikachi/templates/kapchikachi/products_info1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>같이가치-shopping-강아지 에어팟 프로케이스</title>
    {% load static %}  
    <link rel="stylesheet" href = "{%static 'css/styles.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script type = "text/javascript" src = "https://d3js.org/d3.v4.min.js"></script>
    <!--자동 업데이트 로직(수정 금지)-->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
    <script type="text/javascript">
   // var auto_refresh = setInterval(
   // function ()
   // {
     //   $('#load_tweets').load('refresh.html').fadeIn("slow");
//}, 5000);
</script>
<!--자동 업데이트 로직(수정 금지)-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" 
    integrity="sha384-Smlep5jCw/wG7hdkwQ/
    Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" 
    integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</head>


<body style="background-color:white;">
        <!--사이트 헤더-->
        <header class="header bg-white bg-opacity-100" >
    

            {% load socialaccount %}
            {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-6">
                    
            </div>
            <div class="col-6">
                <a style="font-family:GyeonggiTitleM;float:right;text-decoration:none;" href="{% url 'common:logout' %}">로그아웃</a><br>
                <a href="{% url 'kapchikachi:Check_personal_buy' %}" style="font-family: GyeonggiTitleM;float: right;text-decoration:none;">구매이력</a></div>
                
               
            </div>
            </div>
        <!--    개인 계정 페이지로 이동(개인정보확인 및 수정/ 구매내역 확인)-->
        {% else %}
        <div class="row">
            <div class="col-6">
                <a style="font-family:GyeonggiTitleM;float:left;text-decoration:none;"></a></div>
            <div class="col-6">
                <a href="{% url 'common:login' %}" style="font-family: GyeonggiTitleM;float:right;">Log-in</a>
            </div>
        </div>
        {% endif %}
    
        
        
         <span class="site-heading"style="text-align :center;">
            <div class="row"><a href="{% url 'kapchikachi:main' %}"><img src="{%static 'img/logo2-remove.png'%}" style="max-width: 200px;max-height: 200px;margin-left: auto;margin-right: auto;"></a></div>
                <div class="row"style="background-color:blanchedalmond;padding-bottom:10px;padding-top: 10px;" >   
                    <div class="col-4"><a href="{% url 'kapchikachi:main' %}" style="font-family:GyeonggiTitleM;font-size:2.5vh;padding-top: 5px;text-decoration:none;"><b>Home</b></a></div>
                    <div class="col-4"><a href="{% url 'kapchikachi:Products' %}" style="font-family:GyeonggiTitleM;font-size:2.5vh;"><b>Products</b></a></div>
                   
                    <div class="col-4"><a href="{% url 'kapchikachi:SelectPayOption' %}" id ="Shopping"style="font-family:GyeonggiTitleM;font-size:2.5vh;padding-top: 5px;text-decoration:none;"><b>Shopping</b></a></div>
            </div>    
        </span>
    </header> 

        


<!--코멘트 생성 기능-->
<div class="container">
<p style="font-family: GyeonggiTitleM;">shopping>강아지 에어팟1 • 2세대 케이스</p>
<div class="row"style="margin-bottom:20px;border:3px black dasehd">
    <p style="font-family: GyeonggiTitleM;font-size: 3vh;text-align: center;">강아지 에어팟 1  •  2 세대 케이스</p>


        
<img src="{%static 'img/dogairpod12.jpg'%}" style="align-content: center;margin-left: auto;margin-right: auto;width:400px;height: 400px; margin-bottom: 10px;" class="img-fluid">

</div>
<section class="page-section about-heading" >
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-3">
                        <p style="font-family: GyeonggiTitleM;font-size: 3vh;border-bottom: black dashed 1px;">가격 : 8,900원</p>
                        <p style="font-family:  GyeonggiTitleM;font-size: 3vh;">상품소개</p>
                        <p class="mb-0">
                            귀여운 말티즈가 프린트 되어있는 에어팟  1  •  2 세대 케이스입니다:)<br>
                            
                           
                        </p>
                        <button style="align-content: center;width: 100px; float: right;margin-top: 40px;"class="btn btn-secondary" onclick=location.href="{% url 'kapchikachi:CommentCreate' %}">구매하기</button>
                    </div>
                </div>
                

            </div>
            
        </div>
        


    </div>
    
</section>

</div>
</div>


<address class="footer text-faded text-center" style="display:block; width:100%;padding-top: 15px;padding-bottom: 3rempx;" >
    <div class="row" >
        <div class="col-3" >
            <a href="{% url 'kapchikachi:Qna' %}" style="color:wheat;font-size:10px;font-family:GyeonggiTitleM ;text-decoration:none;"> QnA </a>
        </div>

        <div  class="col-3">
            <a href="{% url 'kapchikachi:Notice_info' %}" style="color:wheat;font-size:10px;font-family:GyeonggiTitleM;text-decoration:none;"> 개인정보처리방침</a> 
        </div>
   

        <div class="col-3">
            <a href="{% url 'kapchikachi:Notice_info' %}" style="color:wheat;font-size:10px;font-family:GyeonggiTitleM;text-decoration:none;"> 사업자 정보 </a> 
        </div>

        <div class="col-3">
            <a href="{% url 'kapchikachi:Notice_info' %}" style="color:wheat;font-size:10px;font-family:GyeonggiTitleM;text-decoration:none;"> 이용약관</a> 
        </div>
    </div>

    <div class="row" style="border-top: 1px solid black;margin-top:15px">
        <div class="col-6" style="margin-top: 10px;">
            <p style="font-family:GyeonggiTitleM;font-size:3vh;color:wheat"> CALL CENTER</p><br>
            <p style="font-family:GyeonggiTitleM;font-size:2vh">010-6378-9438 </p>
            <p style="font-family:GyeonggiTitleM;font-size:1.5vh">Open Am 10 : 00 – PM 05 : 00 </p>
            <p style="font-family:GyeonggiTitleM;font-size:1.5vh">LUNCH PM 12 : 30 ~ 1 : 30 </p>
            <p style="font-family:GyeonggiTitleM;font-size:1.5vh"><a href="https://open.kakao.com/me/value_together" style="font-family:GyeonggiTitleM;font-size:1.5vh;color:wheat;margin-top:2px;">오픈카카오톡</a></p>
        </div>

        <div class="col-6" style="margin-top: 10px;">
            <p style="font-family:GyeonggiTitleM;font-size:3vh;color:wheat"> Sponsor Us</p><br>
            <p style="font-family:GyeonggiTitleM;font-size:2vh"> 국민 92030201552024</p>
            <p style="font-family:GyeonggiTitleM;font-size:1.5vh">Instagram <br>
                <a style="font-family:GyeonggiTitleM;font-size:1.5vh;color:wheat;margin-top:2px;" href="https://www.instagram.com/value__together/">@value__together</a></p>
            
        </div>
        <div class="img-fluid"><img src="{%static 'img/valtowhite.png'%}" style=" max-width: 100px;max-height: 
            100px;margin-left:auto;padding:0px; "></div>
    
</address>
>
    

</body>
   <!-- Bootstrap core JS-->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
   <!-- Core theme JS-->
   <script src="{%static 'Js/script.js'%}"></script>
   <script src="{%static 'Js/chart.js'%}"></script>
</html>